source "${HOME}/.zgen/zgen.zsh"

if ! zgen saved; then
  echo "Creating a zgen save"

  zgen oh-my-zsh

  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/cp
  zgen oh-my-zsh plugins/history
  zgen oh-my-zsh plugins/python
  zgen oh-my-zsh plugins/ruby
  zgen oh-my-zsh plugins/ssh-agent
  zgen oh-my-zsh plugins/composer
  zgen oh-my-zsh plugins/laravel5

  zgen load nojhan/liquidprompt

  zgen load bobthecow/git-flow-completion

  zgen load chrissicool/zsh-256color
  zgen load joel-porquet/zsh-dircolors-solarized
  zgen load rimraf/k

  # Have to be last
  zgen load willghatch/zsh-cdr
  zgen load zsh-users/zaw

  zgen save
fi

if command -v nvim 2>/dev/null >&2; then
    alias vim="nvim"
    export EDITOR="nvim"
else
    export EDITOR="vim"
fi

if [[ -e ~/.zsh_local ]]; then
    source ~/.zsh_local
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
