#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$headers = array('accept' => 'application/json');
$json = Requests::get('http://ets2mpstats.com/api/etr/dj/en', $headers);

$decode = json_decode($json->body);

echo $decode->dj;
