#!/usr/bin/env sh

DYNAMIC_ISLAND_DIR="$HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar"
ITEMS_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

# Define Dynamic island custom configs here
source "$DYNAMIC_ISLAND_DIR/config.sh" # Loads Dynamic-Island config

# run helper program
ISLANDHELPER=git.crissnb.islandhelper
killall islandhelper
cd $DYNAMIC_ISLAND_DIR/helper && make
$DYNAMIC_ISLAND_DIR/helper/islandhelper $ISLANDHELPER &

# Set up your own custom sketchybar config here

sketchybar --default icon.font="Hack Nerd Font:Bold:17.0"  \
                     icon.color=0xffffffff                 \
                     label.font="Hack Nerd Font:Bold:14.0" \
                     label.color=0xffffffff                \
                     padding_left=5                        \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=4                 \
                     icon.padding_left=4                   \
                     icon.padding_right=4

###############################################

source "$DYNAMIC_ISLAND_DIR/item.sh" # Loads Dynamic-Island item
source "$ITEMS_DIR/yabai.sh"
source "$ITEMS_DIR/front_app.sh"
source "$ITEMS_DIR/clock.sh"
source "$ITEMS_DIR/wifi.sh"
source "$ITEMS_DIR/volume.sh"

sketchybar --update
